// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InvoiceGenerator.proto

package com.example.invoice.grpc;

public interface InvoiceGeneratorServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.invoice.InvoiceGeneratorServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>sint64 responseCode = 2;</code>
   * @return The responseCode.
   */
  long getResponseCode();
}
