// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InvoiceGenerator.proto

package com.example.invoice.grpc;

public final class InvoiceGenerator {
  private InvoiceGenerator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_invoice_InvoiceGeneratorServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_invoice_InvoiceGeneratorServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_invoice_InvoiceGeneratorServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_invoice_InvoiceGeneratorServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026InvoiceGenerator.proto\022\023com.example.in" +
      "voice\"\351\001\n\036InvoiceGeneratorServiceRequest" +
      "\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022\r\n" +
      "\005email\030\003 \001(\t\022\016\n\006amount\030\004 \001(\022\022N\n\014purchase" +
      "Type\030\005 \001(\01628.com.example.invoice.Invoice" +
      "GeneratorServiceRequest.Type\"3\n\004Type\022\013\n\007" +
      "UNKNOWN\020\000\022\014\n\010PURCHASE\020\001\022\020\n\014SUBSCRIPTION\020" +
      "\002\"P\n\037InvoiceGeneratorServiceResponse\022\027\n\017" +
      "responseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 " +
      "\001(\0222\240\001\n\027InvoiceGeneratorService\022\204\001\n\027Invo" +
      "iceGeneratorService\0223.com.example.invoic" +
      "e.InvoiceGeneratorServiceRequest\0324.com.e" +
      "xample.invoice.InvoiceGeneratorServiceRe" +
      "sponseB\034\n\030com.example.invoice.grpcP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_invoice_InvoiceGeneratorServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_invoice_InvoiceGeneratorServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_invoice_InvoiceGeneratorServiceRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Amount", "PurchaseType", });
    internal_static_com_example_invoice_InvoiceGeneratorServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_invoice_InvoiceGeneratorServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_invoice_InvoiceGeneratorServiceResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
